PREFIX = /usr/local
CC     = gcc
CXX    = g++

M2ROOT = $(PREFIX)/minix2
M2BIN  = $(M2ROOT)/usr/bin
M2LIB  = $(M2ROOT)/usr/lib

V6ROOT = $(PREFIX)/v6root
V6BIN  = $(V6ROOT)/bin
V6LIB  = $(V6ROOT)/lib

V7ROOT = $(PREFIX)/v7root
V7BIN  = $(V7ROOT)/bin
V7LIB  = $(V7ROOT)/lib

ACKROOT= $(PREFIX)/8086v6-ack
ACKBIN = $(ACKROOT)/bin
ACKLIB = $(ACKROOT)/lib

MINGW  = #i686-mingw32-
